name: Build docker image

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 2' # 3am Tuesday UTC

env:
  VERSION: 1.11.0
  IMAGE: ghcr.io/sondrelg/moldy-chef

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: amd64
            arch: x86_64
          - platform: arm64
            arch: aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          platforms: linux/${{ matrix.platform }}
          build-args: |
            VERSION=${{ env.VERSION }}
            ARCH=${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.IMAGE }}-${{ matrix.platform }}:latest,${{ env.IMAGE }}-${{ matrix.platform }}:${{ github.sha }}

  create-manifest:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Create SHA manifest and push
        run: |
          docker buildx imagetools create -t "${{ env.IMAGE }}:${{ github.sha }}" \
            "${{ env.IMAGE }}-amd64:${{ github.sha }}" \
            "${{ env.IMAGE }}-arm64:${{ github.sha }}"
      - name: Create latest manifest and push
        run: |
          docker buildx imagetools create -t "${{ env.IMAGE }}:latest" \
            "${{ env.IMAGE }}-amd64:latest" \
            "${{ env.IMAGE }}-arm64:latest"
